## MANUAL LOCK
bindsym $mod+l exec /home/dirtyak/.config/sway/scripts/blur-lock &

## IDLE MANAGER
exec swayidle -w \
	timeout 120 '/home/dirtyak/.config/sway/scripts/blur-lock &' \
	timeout 600 'systemctl suspend' \
		resume 'notify-send "Session" "Resume"'
