### Workspace configuration
#

# default workspace layout
workspace_layout default

# Define names for default workspaces
#set $ws1 "1:"
#set $ws2 "2:"
#set $ws3 "3:"
#set $ws4 "4:"
#set $ws5 "5:"
#set $ws6 "6:"
#set $ws7 "7:"
#set $ws8 "8:"
#set $ws9 "9"
#set $ws10 "10"
set $ws1 1
set $ws2 2
set $ws3 3
set $ws4 4
set $ws5 5
set $ws6 6
set $ws7 7
set $ws8 8
set $ws9 9
set $ws10 10

# bind program to workspace and focus to them on startup:
assign [class="Xfce4-terminal"] $ws1
assign [class="Alacritty"] $ws1
assign [class="(?i)firefox"] $ws2
assign [class="Thunar"] $ws3
assign [class="thunderbird"] $ws4
assign [class="Ferdium"] $ws4
assign [class="TelegramDesktop"] $ws4
assign [class="Cursor"] $ws5
assign [class="steam"] $ws6
assign [class="steamwebhelper"] $ws6
assign [class="Protonvpn-app"] $ws7
assign [class="VirtualBox"] $ws8

# automatic set focus new window if it opens on another workspace than the current:
for_window [class=Xfce4-terminal] focus
for_window [class=Alacritty] focus
for_window [class=(?i)firefox] focus
for_window [class=Thunar] focus
for_window [class=Thunderbird] focus
for_window [class=TelegramDesktop] focus

# Guake terminal settings
for_window [class="Guake"] floating enable
for_window [class="Guake"] sticky enable
for_window [class="Guake"] border none
for_window [class="Guake"] move position 0 0

#assign [class="Xfce4-terminal"] $ws1
#assign [class="Alacritty"] $ws1
assign [class="(?i)firefox"] $ws2
assign [class="Thunar"] $ws3
assign [class="thunderbird"] $ws4
assign [class="Ferdium"] $ws4
assign [class="TelegramDesktop"] $ws4
assign [class="Cursor"] $ws5
assign [class="steam"] $ws6
assign [class="steamwebhelper"] $ws6
assign [class="Protonvpn-app"] $ws7
assign [class="VirtualBox"] $ws8

# automatic set focus new window if it opens on another workspace than the current:
for_window [class=Xfce4-terminal] focus
for_window [class=Alacritty] focus
for_window [class=(?i)firefox] focus
for_window [class=Thunar] focus
for_window [class=Thunderbird] focus
for_window [class=TelegramDesktop] focus


##################
# floating rules #
##################

# Make some apps floating
for_window [app_id="Alacritty"] floating enable
for_window [class="VirtualBox"] floating enable
for_window [class="Yad" instance="yad"] floating enable
for_window [class="Galculator" instance="galculator"] floating enable
for_window [class="Blueberry.py" instance="blueberry.py"] floating enable
for_window [class="Xsane" instance="xsane"] floating enable
for_window [class="Pavucontrol" instance="pavucontrol"] floating enable
for_window [class="qt5ct" instance="qt5ct"] floating enable
for_window [class="Blueberry.py" instance="blueberry.py"] floating enable
for_window [class="Bluetooth-sendto" instance="bluetooth-sendto"] floating enable
for_window [class="Pamac-manager"] floating enable
for_window [window_role="About"] floating enable

# set border of floating window
for_window [class="urxvt"] border pixel 1

# set size of floating window
#for_window [window_role="(?i)GtkFileChooserDialog"] resize set 640 480 #to set size of file choose dialog
#for_window [class=".*"] resize set 640 480 #to change size of all floating windows 

# set position of floating window
# for_window [class=".*"] move position center

# Manage the dropdown terminal
for_window [app_id="dropdown"] \
    floating enable, \
    resize set 100% 40%, \
    move position center, \
    move to scratchpad, \
    scratchpad show
