
#############################################
# autostart applications/services on login: #
#############################################
exec_always --no-startup-id picom --config  ~/.config/picom.conf
exec_always --no-startup-id pgrep waybar || waybar
exec wl-paste -t text --watch clipman store --no-persist


## IDLE MANAGER
exec swayidle -w \
	timeout 120 '/home/dirtyak/.config/sway/scripts/blur-lock &' \
	timeout 600 'systemctl suspend' \
		resume 'notify-send "Session" "Resume"'

# AUTH by POLICYKIT
#exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec lxqt-policykit-agent

# dex is a tool that automatically starts XDG-compliant autostart entries
# It reads .desktop files from ~/.config/autostart/ and /etc/xdg/autostart/
exec --no-startup-id dex --autostart --environment wayland

# start welcome app
# exec --no-startup-id sh /usr/share/endeavouros/scripts/welcome --startdelay=3 

# set wallpaper
exec sleep 1 && swaybg -i /home/dirtyak/Pictures/wallpaper/foCyHXt-black-hole-wallpapers.jpg

# set powersavings for display:
#exec xset s 480 dpms 600 600 600

## Notify manager
exec --no-startup-id /usr/bin/mako

# Autostart apps as you like
#exec --no-startup-id sleep 2 && alacritty
#exec --no-startup-id sleep 10 && firefox https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/main/force-knowledge.md
#exec --no-startup-id sleep 3 && thunar
exec --no-startup-id sleep 1 && GTK-THEME="Arc-Dark" protonvpn-app
exec --no-startup-id sleep 1 && guake
